### ISSUE TITLE
D3D12 Cheat Menu?

### ISSUE THREAD

**Issue by websecnl** [DestroyerDarkNess/Cheat-Menu-Example#1]
Got any menu like this which is compatible with D3D12 games ?

**Comment by DestroyerDarkNess** [comment]
For some reason, github didn't notify me of the issue. Sorry about delayed answer.

This is Winfoms, GDI. I mean, it works in all games.

However if your game is Direcxt and it is in full screen you will have to make some small adjustments.

I made a post to talk about this and also a solution, Check my Post:

[[Tutorial] How to Overlay Form on Games in "Full Screen"](https://foro.elhacker.net/net_c_vbnet_asp/tutorial_como_superponer_form_sobre_juegos_en_pantalla_completa-t507078.0.html)
